---
extends:
  - standard
  - plugin:import/recommended
  - plugin:import/typescript # this line does the trick
  - prettier

# or configure manually:
plugins:
  - import
  - promise
  - standard
  - '@typescript-eslint'
  - 'prettier'

parser: '@typescript-eslint/parser'

parserOptions:
  sourceType: module
  ecmaVersion: 6

rules:
  comma-dangle: off
  "import/order": "error"
  "no-unused-vars": "off"
  "@typescript-eslint/no-unused-vars": ["error"]
  "semi": ["error", "always"]
